---
# defaults file for netbox
ntp_servers:
  - 162.159.200.1
  - 162.159.200.123
dns_servers:
  - 1.1.1.3
  - 9.9.9.9
sites:
  - name: "MINNESOTA01"
    time_zone: America/Chicago
    status: active
    description: Dev
  - name: "MINNESOTA02"
    time_zone: America/Chicago
    status: active
    description: Dev
racks:
  - name: "MN_01"
    site: "MINNESOTA01"
manufacturers:
  - Arista
  - Cisco
  - CustomBuild
  - Raspberry Pi
device_types:
  - {"model": "ASAv", "manufacturer": "Cisco", "slug": "asav", "part_number": "asav", "full_depth": False}
  - {"model": "CSR1000v", "manufacturer": "Cisco", "slug": "csr1000v", "part_number": "csr1000v", "full_depth": False}
  - {"model": "CustomServer", "manufacturer": "CustomBuild", "slug": "customserver", "part_number": "home", "full_depth": True}
  - {"model": "IOSv", "manufacturer": "Cisco", "slug": "iosv", "part_number": "iosv", "full_depth": False}
  - {"model": "nx-osv-chassis-nx-osv-supervisor-module", "manufacturer": "Cisco", "slug": "nx-osv-chassis-nx-osv-supervisor-module", "part_number": "nx-osv-chassis-nx-osv-supervisor-module", "full_depth": False}
  - {"model": "nxosv", "manufacturer": "Cisco", "slug": "nxosv", "part_number": "nxosv", "full_depth": False}
  - {"model": "vEOS", "manufacturer": "Arista", "slug": "veos", "part_number": "veos", "full_depth": False}





vlans:
  - { vid: 100, desc: Demo VLAN }
  - { vid: 200, desc: Primary VLAN }
  - { vid: 300, desc: Secondary VLAN }
rirs:
  - name: RFC1918
    is_private: True
aggregates:
  - { name: "10.0.0.0/8", desc: RFC1918 - 10, rir: RFC1918 }
  - { name: "172.16.0.0/12", desc: RFC1918 - 172, rir: RFC1918 }
  - { name: "192.0.2.0/24", desc: RFC5735 - 192.0.2.0, rir: RFC1918 }
  - { name: "192.168.0.0/16", desc: RFC1918 - 192, rir: RFC1918 }
prefixes:
  - { prefix: 10.50.50.0/24, desc: GNS3 Loopbacks, ispool: true }
  - { prefix: 172.31.0.0/24, desc: GNS3 - DC, ispool: false }
  - { prefix: 172.31.1.0/24, desc: GNS3 - DC Mgmt, ispool: false }
  - { prefix: 192.168.0.0/24, desc: GNS3 Remote, ispool: false }
  - { prefix: 192.0.2.0/24, desc: Example Network, ispool: true }
circuit_providers:
  - name: Charter Spectrum
    asn: 7843
    account: in_good_standing
    portal_url: http://spectrum.net
    noc_contact: noc@spectrum.net
    comments: "Cable Provider"
circuit_types:
  - name: Cable
circuits:
  - cid: my-circuit-id
    provider: Charter Spectrum
    circuit_type: Cable
    status: Active
    install_date: "2016-06-01"
    commit_rate: 200000000
    description: Charter Spectrum Cable Internet
    comments: "Delivered"



cluster:
  - { name: "Proxmox-FFM", cluster_type: "Proxmox", cluster_group: "Proxmox", site: "FFM", tenant_group: "3ascloud", tenant: "3ascloud" }
  - { name: "Proxmox-FKB", cluster_type: "Proxmox", cluster_group: "Proxmox", site: "FKB", tenant_group: "3ascloud", tenant: "3ascloud" }

cluster_group:
  - { name: "Proxmox"}

cluster_type: 
  - { name: "Proxmox"}

tenant_group:
  - { name: "3ascloud"}
  - { name: "kubermatic"}

tenant:
  - { name: "3ascloud", tenant_group: "3ascloud"}
  - { name: "kubermatic", tenant_group: "kubermatic"}
  - { name: "RKI", tenant_group: "kubermatic"}
  - { name: "BHYP RITA", tenant_group: "kubermatic"}
  - { name: "BHYP PM2", tenant_group: "kubermatic"}

region:
  - { name: "Frankfurt"}
  - { name: "Karlsruhe"}

site_group:
  - { name: "Frankfurt"}
  - { name: "Karlsruhe"}

site:
  - { name: "FFM", site_group: "Frankfurt", region: "Frankfurt", tenant: "3ascloud", time_zone: "Europe/Berlin"}
  - { name: "FKB", site_group: "Karlsruhe", region: "Karlsruhe", tenant: "3ascloud", time_zone: "Europe/Berlin"}

manufacturer:
  - { name: "Dell"}

device_type:
  - {model: "PowerEdge R650xs", manufacturer: "Dell", u_height: 1, weight: 18.62, weight_unit: "kg", is_full_depth: True}

device_roles:
  - { name: Firewall, color: FF0000, vm_role: true }
  - { name: Router, color: 000080, vm_role: true }
  - { name: Server, color: "000000", vm_role: false }
  - { name: Switch, color: 008000, vm_role: true }
  - { name: VM, color: 00FFFF, vm_role: true }

platforms:
  - { name: Ubuntu 18.04, slug: ubuntu1804 }
  - { name: Ubuntu 16.04, slug: ubuntu1604 }
  - { name: Ubuntu 20.04, slug: ubuntu2004 }
  - { name: Ubuntu 22.04, slug: ubuntu2204 }
  - { name: Windows 2016, slug: win2016 }
  - { name: Windows 2019, slug: win2019 }
  - { name: Rocky 8, slug: rocky8 }
  - { name: Rocky 9, slug: rocky9 }


device:
  - { name: "Proxmox-FFM-01", device_type: "PowerEdge R650xs", device_role: "Server", tenant: "3ascloud", platform: "ubuntu2204", site: "FFM", cluster: "Proxmox-FFM"}
  - { name: "Proxmox-FKB-01", device_type: "PowerEdge R650xs", device_role: "Server", tenant: "3ascloud", platform: "ubuntu2204", site: "FKB", cluster: "Proxmox-FKB"}



virtual_machine:
  - { name: "VM-FFM-01", site: "FFM", cluster: "Proxmox-FFM", virtual_machine_role: "VM", vcpus: "4", tenant: "kubermatic", platform: "ubuntu2204", primary_ip4: "10.0.0.0", memory: "4096", disk: "30"}
  - { name: "VM-FFM-02", site: "FFM", cluster: "Proxmox-FFM", virtual_machine_role: "VM", vcpus: "4", tenant: "kubermatic", platform: "ubuntu2204", primary_ip4: "10.0.0.0", memory: "4096", disk: "30"}
  - { name: "VM-FFM-03", site: "FFM", cluster: "Proxmox-FFM", virtual_machine_role: "VM", vcpus: "4", tenant: "kubermatic", platform: "ubuntu2204", primary_ip4: "10.0.0.0", memory: "4096", disk: "30"}
  - { name: "VM-FKB-01", site: "FKB", cluster: "Proxmox-FKB", virtual_machine_role: "VM", vcpus: "4", tenant: "kubermatic", platform: "ubuntu2204", primary_ip4: "10.0.0.0", memory: "4096", disk: "30"}
  - { name: "VM-FKB-02", site: "FKB", cluster: "Proxmox-FKB", virtual_machine_role: "VM", vcpus: "4", tenant: "kubermatic", platform: "ubuntu2204", primary_ip4: "10.0.0.0", memory: "4096", disk: "30"}


  # vars:
  #   install_state: present
  #   vms:
  #     - { name: gns3, address: 192.168.0.101/24 }
  #     - { name: awx, address: 192.168.0.102/24 }
  #     - { name: netbox03, address: 192.168.0.103/24 }
  #     - { name: prometheus, address: 192.168.0.104/24 }
  #     - { name: docker01, address: 192.168.0.105/24 }
  #     - { name: docker02, address: 192.168.0.106/24 }
  #   pves:
  #     - { name: pve01, address: "192.168.0.254/24" }
  #     - { name: pve02, address: "192.168.0.253/24" }
  #   netbox_headers:
  #     Content-Type: "application/json"
  #     Authorization: "token {{ lookup('env', 'NETBOX_API_KEY') }}"
  #   netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
  #   netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"